### ISSUE TITLE
Machine Type and Ingredients

### ISSUE THREAD

**Issue by Jeroendevr** [BobLuursema/Factorio#1]
Hi @BobLuursema ,

Within the code what do you mean for machine_type. I would like to add Iron Ore to the database, but I don't know which parameter to put in for machine_type. Is it possible we could define the different types?
@Update nevermind fount it in the factorio_orm file. It should be "Drill"

Second question Iron Ore does not really has an ingredient what then?

**Comment by BobLuursema** [comment]
I am not terribly sure what solution I used, you should be able to find it in my database file. If I remember correctly you just don't put in an ingredient.

_Sent from my Motorola MotoG3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
